apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80   # <---- Change from 3000 to 80
